// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVfL2hcaDk3vTO8y-0wg9vx0rwya9FhRM',
    appId: '1:878848525246:web:eda2d37f98d9d9ab5f6fef',
    messagingSenderId: '878848525246',
    projectId: 'ambw-ichallengeyou',
    authDomain: 'ambw-ichallengeyou.firebaseapp.com',
    storageBucket: 'ambw-ichallengeyou.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwSkbwktbddx5w30YDoSZwAC5WFLLWgyQ',
    appId: '1:878848525246:android:bf14bf1e48ff97b95f6fef',
    messagingSenderId: '878848525246',
    projectId: 'ambw-ichallengeyou',
    storageBucket: 'ambw-ichallengeyou.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9urVXnwWTX-yZYSUOWdjfwfgY89esdxQ',
    appId: '1:878848525246:ios:038b2eb5616418645f6fef',
    messagingSenderId: '878848525246',
    projectId: 'ambw-ichallengeyou',
    storageBucket: 'ambw-ichallengeyou.appspot.com',
    iosClientId: '878848525246-po43q4ar37v2lr3k38gna953rf7i02in.apps.googleusercontent.com',
    iosBundleId: 'com.example.ichallengeyouapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9urVXnwWTX-yZYSUOWdjfwfgY89esdxQ',
    appId: '1:878848525246:ios:038b2eb5616418645f6fef',
    messagingSenderId: '878848525246',
    projectId: 'ambw-ichallengeyou',
    storageBucket: 'ambw-ichallengeyou.appspot.com',
    iosClientId: '878848525246-po43q4ar37v2lr3k38gna953rf7i02in.apps.googleusercontent.com',
    iosBundleId: 'com.example.ichallengeyouapp',
  );
}
